resources:
  requests:
    cpu: 10m
    memory: 24Mi
  limits:
    cpu: 100m
    memory: 32Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 24Mi
    limits:
      cpu: 100m
      memory: 32Mi

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu: 100m
      memory: 48Mi
